[book]
authors = ["NayJi7"]
language = "en"
src = "src"
title = "Gitoui"
description = "Gitoui Documentation"

[output.html]
git-repository-url = "https://github.com/NayJi7/gitoui"
site-url = "/gitoui/"
default-theme = "rust"
