use ratatui::style::Color;
use crate::color::ColorTheme;

pub struct ThemeDefinition {
    pub color_theme: ColorTheme,
    /// Name of the syntect syntax theme to use for diff highlighting.
    pub syntax_theme: &'static str,
}

pub fn list_themes() -> &'static [&'static str] {
    &[
        "Tokyo Night",
        "Dracula",
        "Catppuccin Mocha",
        "Catppuccin Latte",
        "Gruvbox Dark",
        "Nord",
        "Solarized Dark",
        "Solarized Light",
        "One Dark",
        "Monokai Pro",
    ]
}

pub fn get_theme(name: &str) -> Option<ThemeDefinition> {
    match name {
        "Tokyo Night"      => Some(tokyo_night()),
        "Dracula"          => Some(dracula()),
        "Catppuccin Mocha" => Some(catppuccin_mocha()),
        "Catppuccin Latte" => Some(catppuccin_latte()),
        "Gruvbox Dark"     => Some(gruvbox_dark()),
        "Nord"             => Some(nord()),
        "Solarized Dark"   => Some(solarized_dark()),
        "Solarized Light"  => Some(solarized_light()),
        "One Dark"         => Some(one_dark()),
        "Monokai Pro"      => Some(monokai_pro()),
        _                  => None,
    }
}

const fn rgb(r: u8, g: u8, b: u8) -> Color { Color::Rgb(r, g, b) }

fn tokyo_night() -> ThemeDefinition {
    ThemeDefinition {
        syntax_theme: "base16-ocean.dark",
        color_theme: ColorTheme {
            bg:                             rgb(0x1a, 0x1b, 0x26),
            fg:                             rgb(0xa9, 0xb1, 0xd6),
            list_selected_fg:               rgb(0xc0, 0xca, 0xf5),
            list_selected_bg:               rgb(0x51, 0x5c, 0x7e),
            list_ref_paren_fg:              rgb(0x51, 0x59, 0x7d),
            list_ref_branch_fg:             rgb(0x9e, 0xce, 0x6a),
            list_ref_remote_branch_fg:      rgb(0xf7, 0x76, 0x8e),
            list_ref_tag_fg:                rgb(0xe0, 0xaf, 0x68),
            list_ref_stash_fg:              rgb(0xbb, 0x9a, 0xf7),
            list_head_fg:                   rgb(0x7d, 0xcf, 0xff),
            list_commit_message_fg:         rgb(0xa9, 0xb1, 0xd6),
            list_name_fg:                   rgb(0x7d, 0xcf, 0xff),
            list_hash_fg:                   rgb(0xe0, 0xaf, 0x68),
            list_date_fg:                   rgb(0xbb, 0x9a, 0xf7),
            list_match_fg:                  rgb(0x1a, 0x1b, 0x26),
            list_match_bg:                  rgb(0xe0, 0xaf, 0x68),
            detail_label_fg:                rgb(0x51, 0x59, 0x7d),
            detail_name_fg:                 rgb(0x7d, 0xcf, 0xff),
            detail_date_fg:                 rgb(0xbb, 0x9a, 0xf7),
            detail_email_fg:                rgb(0x7a, 0xa2, 0xf7),
            detail_hash_fg:                 rgb(0xe0, 0xaf, 0x68),
            detail_ref_branch_fg:           rgb(0x9e, 0xce, 0x6a),
            detail_ref_remote_branch_fg:    rgb(0xf7, 0x76, 0x8e),
            detail_ref_tag_fg:              rgb(0xe0, 0xaf, 0x68),
            detail_file_change_add_fg:      rgb(0x9e, 0xce, 0x6a),
            detail_file_change_modify_fg:   rgb(0xff, 0x9e, 0x64),
            detail_file_change_delete_fg:   rgb(0xf7, 0x76, 0x8e),
            detail_file_change_move_fg:     rgb(0x7d, 0xcf, 0xff),
            ref_selected_fg:                rgb(0xc0, 0xca, 0xf5),
            ref_selected_bg:                rgb(0x51, 0x5c, 0x7e),
            help_block_title_fg:            rgb(0x9e, 0xce, 0x6a),
            help_key_fg:                    rgb(0xe0, 0xaf, 0x68),
            virtual_cursor_fg:              Color::Reset,
            status_input_fg:                Color::Reset,
            status_input_transient_fg:      rgb(0x51, 0x59, 0x7d),
            status_info_fg:                 rgb(0x7d, 0xcf, 0xff),
            status_success_fg:              rgb(0x9e, 0xce, 0x6a),
            status_warn_fg:                 rgb(0xe0, 0xaf, 0x68),
            status_error_fg:                rgb(0xf7, 0x76, 0x8e),
            divider_fg:                     rgb(0x3b, 0x42, 0x61),
        },
    }
}

fn dracula() -> ThemeDefinition {
    ThemeDefinition {
        syntax_theme: "Dracula",
        color_theme: ColorTheme {
            bg:                             rgb(0x28, 0x2a, 0x36),
            fg:                             rgb(0xf8, 0xf8, 0xf2),
            list_selected_fg:               rgb(0xf8, 0xf8, 0xf2),
            list_selected_bg:               rgb(0x44, 0x47, 0x5a),
            list_ref_paren_fg:              rgb(0x62, 0x72, 0xa4),
            list_ref_branch_fg:             rgb(0x50, 0xfa, 0x7b),
            list_ref_remote_branch_fg:      rgb(0xff, 0x55, 0x55),
            list_ref_tag_fg:                rgb(0xf1, 0xfa, 0x8c),
            list_ref_stash_fg:              rgb(0xbd, 0x93, 0xf9),
            list_head_fg:                   rgb(0x8b, 0xe9, 0xfd),
            list_commit_message_fg:         rgb(0xf8, 0xf8, 0xf2),
            list_name_fg:                   rgb(0x50, 0xfa, 0x7b),
            list_hash_fg:                   rgb(0xff, 0xb8, 0x6c),
            list_date_fg:                   rgb(0xbd, 0x93, 0xf9),
            list_match_fg:                  rgb(0x28, 0x2a, 0x36),
            list_match_bg:                  rgb(0xf1, 0xfa, 0x8c),
            detail_label_fg:                rgb(0x62, 0x72, 0xa4),
            detail_name_fg:                 rgb(0x50, 0xfa, 0x7b),
            detail_date_fg:                 rgb(0xbd, 0x93, 0xf9),
            detail_email_fg:                rgb(0xff, 0x79, 0xc6),
            detail_hash_fg:                 rgb(0xff, 0xb8, 0x6c),
            detail_ref_branch_fg:           rgb(0x50, 0xfa, 0x7b),
            detail_ref_remote_branch_fg:    rgb(0xff, 0x55, 0x55),
            detail_ref_tag_fg:              rgb(0xf1, 0xfa, 0x8c),
            detail_file_change_add_fg:      rgb(0x50, 0xfa, 0x7b),
            detail_file_change_modify_fg:   rgb(0xff, 0xb8, 0x6c),
            detail_file_change_delete_fg:   rgb(0xff, 0x55, 0x55),
            detail_file_change_move_fg:     rgb(0x8b, 0xe9, 0xfd),
            ref_selected_fg:                rgb(0xf8, 0xf8, 0xf2),
            ref_selected_bg:                rgb(0x44, 0x47, 0x5a),
            help_block_title_fg:            rgb(0x50, 0xfa, 0x7b),
            help_key_fg:                    rgb(0xf1, 0xfa, 0x8c),
            virtual_cursor_fg:              Color::Reset,
            status_input_fg:                Color::Reset,
            status_input_transient_fg:      rgb(0x62, 0x72, 0xa4),
            status_info_fg:                 rgb(0x8b, 0xe9, 0xfd),
            status_success_fg:              rgb(0x50, 0xfa, 0x7b),
            status_warn_fg:                 rgb(0xf1, 0xfa, 0x8c),
            status_error_fg:                rgb(0xff, 0x55, 0x55),
            divider_fg:                     rgb(0x44, 0x47, 0x5a),
        },
    }
}

fn catppuccin_mocha() -> ThemeDefinition {
    ThemeDefinition {
        syntax_theme: "base16-ocean.dark",
        color_theme: ColorTheme {
            bg:                             rgb(0x1e, 0x1e, 0x2e),
            fg:                             rgb(0xcd, 0xd6, 0xf4),
            list_selected_fg:               rgb(0xcd, 0xd6, 0xf4),
            list_selected_bg:               rgb(0x45, 0x47, 0x5a),
            list_ref_paren_fg:              rgb(0x7f, 0x84, 0x9c),
            list_ref_branch_fg:             rgb(0xa6, 0xe3, 0xa1),
            list_ref_remote_branch_fg:      rgb(0xf3, 0x8b, 0xa8),
            list_ref_tag_fg:                rgb(0xf9, 0xe2, 0xaf),
            list_ref_stash_fg:              rgb(0xcb, 0xa6, 0xf7),
            list_head_fg:                   rgb(0x89, 0xb4, 0xfa),
            list_commit_message_fg:         rgb(0xcd, 0xd6, 0xf4),
            list_name_fg:                   rgb(0x89, 0xdc, 0xeb),
            list_hash_fg:                   rgb(0xfa, 0xb3, 0x87),
            list_date_fg:                   rgb(0xcb, 0xa6, 0xf7),
            list_match_fg:                  rgb(0x1e, 0x1e, 0x2e),
            list_match_bg:                  rgb(0xf9, 0xe2, 0xaf),
            detail_label_fg:                rgb(0x7f, 0x84, 0x9c),
            detail_name_fg:                 rgb(0x89, 0xdc, 0xeb),
            detail_date_fg:                 rgb(0xcb, 0xa6, 0xf7),
            detail_email_fg:                rgb(0x89, 0xb4, 0xfa),
            detail_hash_fg:                 rgb(0xfa, 0xb3, 0x87),
            detail_ref_branch_fg:           rgb(0xa6, 0xe3, 0xa1),
            detail_ref_remote_branch_fg:    rgb(0xf3, 0x8b, 0xa8),
            detail_ref_tag_fg:              rgb(0xf9, 0xe2, 0xaf),
            detail_file_change_add_fg:      rgb(0xa6, 0xe3, 0xa1),
            detail_file_change_modify_fg:   rgb(0xfa, 0xb3, 0x87),
            detail_file_change_delete_fg:   rgb(0xf3, 0x8b, 0xa8),
            detail_file_change_move_fg:     rgb(0x94, 0xe2, 0xd5),
            ref_selected_fg:                rgb(0xcd, 0xd6, 0xf4),
            ref_selected_bg:                rgb(0x45, 0x47, 0x5a),
            help_block_title_fg:            rgb(0xa6, 0xe3, 0xa1),
            help_key_fg:                    rgb(0xf9, 0xe2, 0xaf),
            virtual_cursor_fg:              Color::Reset,
            status_input_fg:                Color::Reset,
            status_input_transient_fg:      rgb(0x7f, 0x84, 0x9c),
            status_info_fg:                 rgb(0x89, 0xdc, 0xeb),
            status_success_fg:              rgb(0xa6, 0xe3, 0xa1),
            status_warn_fg:                 rgb(0xf9, 0xe2, 0xaf),
            status_error_fg:                rgb(0xf3, 0x8b, 0xa8),
            divider_fg:                     rgb(0x31, 0x32, 0x44),
        },
    }
}

fn catppuccin_latte() -> ThemeDefinition {
    ThemeDefinition {
        syntax_theme: "Solarized (light)",
        color_theme: ColorTheme {
            bg:                             rgb(0xef, 0xf1, 0xf5),
            fg:                             rgb(0x4c, 0x4f, 0x69),
            list_selected_fg:               rgb(0x4c, 0x4f, 0x69),
            list_selected_bg:               rgb(0xbc, 0xc0, 0xcc),
            list_ref_paren_fg:              rgb(0x8c, 0x8f, 0xa1),
            list_ref_branch_fg:             rgb(0x40, 0xa0, 0x2b),
            list_ref_remote_branch_fg:      rgb(0xd2, 0x0f, 0x39),
            list_ref_tag_fg:                rgb(0xdf, 0x8e, 0x1d),
            list_ref_stash_fg:              rgb(0x88, 0x39, 0xef),
            list_head_fg:                   rgb(0x1e, 0x66, 0xf5),
            list_commit_message_fg:         rgb(0x4c, 0x4f, 0x69),
            list_name_fg:                   rgb(0x04, 0xa5, 0xe5),
            list_hash_fg:                   rgb(0xfe, 0x64, 0x0b),
            list_date_fg:                   rgb(0x88, 0x39, 0xef),
            list_match_fg:                  rgb(0xef, 0xf1, 0xf5),
            list_match_bg:                  rgb(0xdf, 0x8e, 0x1d),
            detail_label_fg:                rgb(0x8c, 0x8f, 0xa1),
            detail_name_fg:                 rgb(0x04, 0xa5, 0xe5),
            detail_date_fg:                 rgb(0x88, 0x39, 0xef),
            detail_email_fg:                rgb(0x1e, 0x66, 0xf5),
            detail_hash_fg:                 rgb(0xdf, 0x8e, 0x1d),
            detail_ref_branch_fg:           rgb(0x40, 0xa0, 0x2b),
            detail_ref_remote_branch_fg:    rgb(0xd2, 0x0f, 0x39),
            detail_ref_tag_fg:              rgb(0xdf, 0x8e, 0x1d),
            detail_file_change_add_fg:      rgb(0x40, 0xa0, 0x2b),
            detail_file_change_modify_fg:   rgb(0xfe, 0x64, 0x0b),
            detail_file_change_delete_fg:   rgb(0xd2, 0x0f, 0x39),
            detail_file_change_move_fg:     rgb(0x17, 0x92, 0x99),
            ref_selected_fg:                rgb(0x4c, 0x4f, 0x69),
            ref_selected_bg:                rgb(0xbc, 0xc0, 0xcc),
            help_block_title_fg:            rgb(0x40, 0xa0, 0x2b),
            help_key_fg:                    rgb(0xdf, 0x8e, 0x1d),
            virtual_cursor_fg:              Color::Reset,
            status_input_fg:                Color::Reset,
            status_input_transient_fg:      rgb(0x8c, 0x8f, 0xa1),
            status_info_fg:                 rgb(0x04, 0xa5, 0xe5),
            status_success_fg:              rgb(0x40, 0xa0, 0x2b),
            status_warn_fg:                 rgb(0xdf, 0x8e, 0x1d),
            status_error_fg:                rgb(0xd2, 0x0f, 0x39),
            divider_fg:                     rgb(0xcc, 0xd0, 0xda),
        },
    }
}

fn gruvbox_dark() -> ThemeDefinition {
    ThemeDefinition {
        syntax_theme: "base16-mocha.dark",
        color_theme: ColorTheme {
            bg:                             rgb(0x28, 0x28, 0x28),
            fg:                             rgb(0xeb, 0xdb, 0xb2),
            list_selected_fg:               rgb(0xfb, 0xf1, 0xc7),
            list_selected_bg:               rgb(0x50, 0x49, 0x45),
            list_ref_paren_fg:              rgb(0x92, 0x83, 0x74),
            list_ref_branch_fg:             rgb(0xb8, 0xbb, 0x26),
            list_ref_remote_branch_fg:      rgb(0xfb, 0x49, 0x34),
            list_ref_tag_fg:                rgb(0xfa, 0xbd, 0x2f),
            list_ref_stash_fg:              rgb(0xd3, 0x86, 0x9b),
            list_head_fg:                   rgb(0x8e, 0xc0, 0x7c),
            list_commit_message_fg:         rgb(0xeb, 0xdb, 0xb2),
            list_name_fg:                   rgb(0x8e, 0xc0, 0x7c),
            list_hash_fg:                   rgb(0xfa, 0xbd, 0x2f),
            list_date_fg:                   rgb(0xd3, 0x86, 0x9b),
            list_match_fg:                  rgb(0x28, 0x28, 0x28),
            list_match_bg:                  rgb(0xfa, 0xbd, 0x2f),
            detail_label_fg:                rgb(0x92, 0x83, 0x74),
            detail_name_fg:                 rgb(0x8e, 0xc0, 0x7c),
            detail_date_fg:                 rgb(0xd3, 0x86, 0x9b),
            detail_email_fg:                rgb(0x83, 0xa5, 0x98),
            detail_hash_fg:                 rgb(0xfa, 0xbd, 0x2f),
            detail_ref_branch_fg:           rgb(0xb8, 0xbb, 0x26),
            detail_ref_remote_branch_fg:    rgb(0xfb, 0x49, 0x34),
            detail_ref_tag_fg:              rgb(0xfa, 0xbd, 0x2f),
            detail_file_change_add_fg:      rgb(0xb8, 0xbb, 0x26),
            detail_file_change_modify_fg:   rgb(0xfe, 0x80, 0x19),
            detail_file_change_delete_fg:   rgb(0xfb, 0x49, 0x34),
            detail_file_change_move_fg:     rgb(0x83, 0xa5, 0x98),
            ref_selected_fg:                rgb(0xfb, 0xf1, 0xc7),
            ref_selected_bg:                rgb(0x50, 0x49, 0x45),
            help_block_title_fg:            rgb(0xb8, 0xbb, 0x26),
            help_key_fg:                    rgb(0xfa, 0xbd, 0x2f),
            virtual_cursor_fg:              Color::Reset,
            status_input_fg:                Color::Reset,
            status_input_transient_fg:      rgb(0x92, 0x83, 0x74),
            status_info_fg:                 rgb(0x8e, 0xc0, 0x7c),
            status_success_fg:              rgb(0xb8, 0xbb, 0x26),
            status_warn_fg:                 rgb(0xfa, 0xbd, 0x2f),
            status_error_fg:                rgb(0xfb, 0x49, 0x34),
            divider_fg:                     rgb(0x3c, 0x38, 0x36),
        },
    }
}

fn nord() -> ThemeDefinition {
    ThemeDefinition {
        syntax_theme: "base16-ocean.dark",
        color_theme: ColorTheme {
            bg:                             rgb(0x2e, 0x34, 0x40),
            fg:                             rgb(0xe5, 0xe9, 0xf0),
            list_selected_fg:               rgb(0xec, 0xef, 0xf4),
            list_selected_bg:               rgb(0x43, 0x4c, 0x5e),
            list_ref_paren_fg:              rgb(0x4c, 0x56, 0x6a),
            list_ref_branch_fg:             rgb(0xa3, 0xbe, 0x8c),
            list_ref_remote_branch_fg:      rgb(0xbf, 0x61, 0x6a),
            list_ref_tag_fg:                rgb(0xeb, 0xcb, 0x8b),
            list_ref_stash_fg:              rgb(0xb4, 0x8e, 0xad),
            list_head_fg:                   rgb(0x88, 0xc0, 0xd0),
            list_commit_message_fg:         rgb(0xd8, 0xde, 0xe9),
            list_name_fg:                   rgb(0x81, 0xa1, 0xc1),
            list_hash_fg:                   rgb(0xeb, 0xcb, 0x8b),
            list_date_fg:                   rgb(0xb4, 0x8e, 0xad),
            list_match_fg:                  rgb(0x2e, 0x34, 0x40),
            list_match_bg:                  rgb(0xeb, 0xcb, 0x8b),
            detail_label_fg:                rgb(0x4c, 0x56, 0x6a),
            detail_name_fg:                 rgb(0x81, 0xa1, 0xc1),
            detail_date_fg:                 rgb(0xb4, 0x8e, 0xad),
            detail_email_fg:                rgb(0x88, 0xc0, 0xd0),
            detail_hash_fg:                 rgb(0xeb, 0xcb, 0x8b),
            detail_ref_branch_fg:           rgb(0xa3, 0xbe, 0x8c),
            detail_ref_remote_branch_fg:    rgb(0xbf, 0x61, 0x6a),
            detail_ref_tag_fg:              rgb(0xeb, 0xcb, 0x8b),
            detail_file_change_add_fg:      rgb(0xa3, 0xbe, 0x8c),
            detail_file_change_modify_fg:   rgb(0xd0, 0x87, 0x70),
            detail_file_change_delete_fg:   rgb(0xbf, 0x61, 0x6a),
            detail_file_change_move_fg:     rgb(0x8f, 0xbc, 0xbb),
            ref_selected_fg:                rgb(0xec, 0xef, 0xf4),
            ref_selected_bg:                rgb(0x43, 0x4c, 0x5e),
            help_block_title_fg:            rgb(0xa3, 0xbe, 0x8c),
            help_key_fg:                    rgb(0xeb, 0xcb, 0x8b),
            virtual_cursor_fg:              Color::Reset,
            status_input_fg:                Color::Reset,
            status_input_transient_fg:      rgb(0x4c, 0x56, 0x6a),
            status_info_fg:                 rgb(0x88, 0xc0, 0xd0),
            status_success_fg:              rgb(0xa3, 0xbe, 0x8c),
            status_warn_fg:                 rgb(0xeb, 0xcb, 0x8b),
            status_error_fg:                rgb(0xbf, 0x61, 0x6a),
            divider_fg:                     rgb(0x3b, 0x42, 0x52),
        },
    }
}

fn solarized_dark() -> ThemeDefinition {
    ThemeDefinition {
        syntax_theme: "Solarized (dark)",
        color_theme: ColorTheme {
            bg:                             rgb(0x00, 0x2b, 0x36),
            fg:                             rgb(0x83, 0x94, 0x96),
            list_selected_fg:               rgb(0x93, 0xa1, 0xa1),
            list_selected_bg:               rgb(0x07, 0x36, 0x42),
            list_ref_paren_fg:              rgb(0x58, 0x6e, 0x75),
            list_ref_branch_fg:             rgb(0x85, 0x99, 0x00),
            list_ref_remote_branch_fg:      rgb(0xdc, 0x32, 0x2f),
            list_ref_tag_fg:                rgb(0xb5, 0x89, 0x00),
            list_ref_stash_fg:              rgb(0x6c, 0x71, 0xc4),
            list_head_fg:                   rgb(0x26, 0x8b, 0xd2),
            list_commit_message_fg:         rgb(0x83, 0x94, 0x96),
            list_name_fg:                   rgb(0x2a, 0xa1, 0x98),
            list_hash_fg:                   rgb(0xb5, 0x89, 0x00),
            list_date_fg:                   rgb(0x6c, 0x71, 0xc4),
            list_match_fg:                  rgb(0x00, 0x2b, 0x36),
            list_match_bg:                  rgb(0xb5, 0x89, 0x00),
            detail_label_fg:                rgb(0x58, 0x6e, 0x75),
            detail_name_fg:                 rgb(0x2a, 0xa1, 0x98),
            detail_date_fg:                 rgb(0x6c, 0x71, 0xc4),
            detail_email_fg:                rgb(0x26, 0x8b, 0xd2),
            detail_hash_fg:                 rgb(0xb5, 0x89, 0x00),
            detail_ref_branch_fg:           rgb(0x85, 0x99, 0x00),
            detail_ref_remote_branch_fg:    rgb(0xdc, 0x32, 0x2f),
            detail_ref_tag_fg:              rgb(0xb5, 0x89, 0x00),
            detail_file_change_add_fg:      rgb(0x85, 0x99, 0x00),
            detail_file_change_modify_fg:   rgb(0xcb, 0x4b, 0x16),
            detail_file_change_delete_fg:   rgb(0xdc, 0x32, 0x2f),
            detail_file_change_move_fg:     rgb(0x2a, 0xa1, 0x98),
            ref_selected_fg:                rgb(0x93, 0xa1, 0xa1),
            ref_selected_bg:                rgb(0x07, 0x36, 0x42),
            help_block_title_fg:            rgb(0x85, 0x99, 0x00),
            help_key_fg:                    rgb(0xb5, 0x89, 0x00),
            virtual_cursor_fg:              Color::Reset,
            status_input_fg:                Color::Reset,
            status_input_transient_fg:      rgb(0x58, 0x6e, 0x75),
            status_info_fg:                 rgb(0x2a, 0xa1, 0x98),
            status_success_fg:              rgb(0x85, 0x99, 0x00),
            status_warn_fg:                 rgb(0xb5, 0x89, 0x00),
            status_error_fg:                rgb(0xdc, 0x32, 0x2f),
            divider_fg:                     rgb(0x07, 0x36, 0x42),
        },
    }
}

fn solarized_light() -> ThemeDefinition {
    ThemeDefinition {
        syntax_theme: "Solarized (light)",
        color_theme: ColorTheme {
            bg:                             rgb(0xfd, 0xf6, 0xe3),
            fg:                             rgb(0x65, 0x7b, 0x83),
            list_selected_fg:               rgb(0x58, 0x6e, 0x75),
            list_selected_bg:               rgb(0xee, 0xe8, 0xd5),
            list_ref_paren_fg:              rgb(0x93, 0xa1, 0xa1),
            list_ref_branch_fg:             rgb(0x85, 0x99, 0x00),
            list_ref_remote_branch_fg:      rgb(0xdc, 0x32, 0x2f),
            list_ref_tag_fg:                rgb(0xb5, 0x89, 0x00),
            list_ref_stash_fg:              rgb(0x6c, 0x71, 0xc4),
            list_head_fg:                   rgb(0x26, 0x8b, 0xd2),
            list_commit_message_fg:         rgb(0x65, 0x7b, 0x83),
            list_name_fg:                   rgb(0x2a, 0xa1, 0x98),
            list_hash_fg:                   rgb(0xb5, 0x89, 0x00),
            list_date_fg:                   rgb(0x6c, 0x71, 0xc4),
            list_match_fg:                  rgb(0xfd, 0xf6, 0xe3),
            list_match_bg:                  rgb(0xb5, 0x89, 0x00),
            detail_label_fg:                rgb(0x93, 0xa1, 0xa1),
            detail_name_fg:                 rgb(0x2a, 0xa1, 0x98),
            detail_date_fg:                 rgb(0x6c, 0x71, 0xc4),
            detail_email_fg:                rgb(0x26, 0x8b, 0xd2),
            detail_hash_fg:                 rgb(0xb5, 0x89, 0x00),
            detail_ref_branch_fg:           rgb(0x85, 0x99, 0x00),
            detail_ref_remote_branch_fg:    rgb(0xdc, 0x32, 0x2f),
            detail_ref_tag_fg:              rgb(0xb5, 0x89, 0x00),
            detail_file_change_add_fg:      rgb(0x85, 0x99, 0x00),
            detail_file_change_modify_fg:   rgb(0xcb, 0x4b, 0x16),
            detail_file_change_delete_fg:   rgb(0xdc, 0x32, 0x2f),
            detail_file_change_move_fg:     rgb(0x2a, 0xa1, 0x98),
            ref_selected_fg:                rgb(0x58, 0x6e, 0x75),
            ref_selected_bg:                rgb(0xee, 0xe8, 0xd5),
            help_block_title_fg:            rgb(0x85, 0x99, 0x00),
            help_key_fg:                    rgb(0xb5, 0x89, 0x00),
            virtual_cursor_fg:              Color::Reset,
            status_input_fg:                Color::Reset,
            status_input_transient_fg:      rgb(0x93, 0xa1, 0xa1),
            status_info_fg:                 rgb(0x2a, 0xa1, 0x98),
            status_success_fg:              rgb(0x85, 0x99, 0x00),
            status_warn_fg:                 rgb(0xb5, 0x89, 0x00),
            status_error_fg:                rgb(0xdc, 0x32, 0x2f),
            divider_fg:                     rgb(0xee, 0xe8, 0xd5),
        },
    }
}

fn one_dark() -> ThemeDefinition {
    ThemeDefinition {
        syntax_theme: "base16-eighties.dark",
        color_theme: ColorTheme {
            bg:                             rgb(0x28, 0x2c, 0x34),
            fg:                             rgb(0xab, 0xb2, 0xbf),
            list_selected_fg:               rgb(0xdc, 0xdf, 0xe4),
            list_selected_bg:               rgb(0x3e, 0x44, 0x51),
            list_ref_paren_fg:              rgb(0x7f, 0x84, 0x8e),
            list_ref_branch_fg:             rgb(0x98, 0xc3, 0x79),
            list_ref_remote_branch_fg:      rgb(0xe0, 0x6c, 0x75),
            list_ref_tag_fg:                rgb(0xe5, 0xc0, 0x7b),
            list_ref_stash_fg:              rgb(0xc6, 0x78, 0xdd),
            list_head_fg:                   rgb(0x61, 0xaf, 0xef),
            list_commit_message_fg:         rgb(0xab, 0xb2, 0xbf),
            list_name_fg:                   rgb(0x56, 0xb6, 0xc2),
            list_hash_fg:                   rgb(0xe5, 0xc0, 0x7b),
            list_date_fg:                   rgb(0xc6, 0x78, 0xdd),
            list_match_fg:                  rgb(0x28, 0x2c, 0x34),
            list_match_bg:                  rgb(0xe5, 0xc0, 0x7b),
            detail_label_fg:                rgb(0x7f, 0x84, 0x8e),
            detail_name_fg:                 rgb(0x56, 0xb6, 0xc2),
            detail_date_fg:                 rgb(0xc6, 0x78, 0xdd),
            detail_email_fg:                rgb(0x61, 0xaf, 0xef),
            detail_hash_fg:                 rgb(0xe5, 0xc0, 0x7b),
            detail_ref_branch_fg:           rgb(0x98, 0xc3, 0x79),
            detail_ref_remote_branch_fg:    rgb(0xe0, 0x6c, 0x75),
            detail_ref_tag_fg:              rgb(0xe5, 0xc0, 0x7b),
            detail_file_change_add_fg:      rgb(0x98, 0xc3, 0x79),
            detail_file_change_modify_fg:   rgb(0xd1, 0x9a, 0x66),
            detail_file_change_delete_fg:   rgb(0xe0, 0x6c, 0x75),
            detail_file_change_move_fg:     rgb(0x56, 0xb6, 0xc2),
            ref_selected_fg:                rgb(0xdc, 0xdf, 0xe4),
            ref_selected_bg:                rgb(0x3e, 0x44, 0x51),
            help_block_title_fg:            rgb(0x98, 0xc3, 0x79),
            help_key_fg:                    rgb(0xe5, 0xc0, 0x7b),
            virtual_cursor_fg:              Color::Reset,
            status_input_fg:                Color::Reset,
            status_input_transient_fg:      rgb(0x7f, 0x84, 0x8e),
            status_info_fg:                 rgb(0x56, 0xb6, 0xc2),
            status_success_fg:              rgb(0x98, 0xc3, 0x79),
            status_warn_fg:                 rgb(0xe5, 0xc0, 0x7b),
            status_error_fg:                rgb(0xe0, 0x6c, 0x75),
            divider_fg:                     rgb(0x3e, 0x44, 0x51),
        },
    }
}

fn monokai_pro() -> ThemeDefinition {
    ThemeDefinition {
        syntax_theme: "Monokai",
        color_theme: ColorTheme {
            bg:                             rgb(0x2d, 0x2a, 0x2e),
            fg:                             rgb(0xfc, 0xfc, 0xfa),
            list_selected_fg:               rgb(0xfc, 0xfc, 0xfa),
            list_selected_bg:               rgb(0x40, 0x3e, 0x41),
            list_ref_paren_fg:              rgb(0x72, 0x70, 0x72),
            list_ref_branch_fg:             rgb(0xa9, 0xdc, 0x76),
            list_ref_remote_branch_fg:      rgb(0xff, 0x61, 0x88),
            list_ref_tag_fg:                rgb(0xff, 0xd8, 0x66),
            list_ref_stash_fg:              rgb(0xab, 0x9d, 0xf2),
            list_head_fg:                   rgb(0x78, 0xdc, 0xe8),
            list_commit_message_fg:         rgb(0xfc, 0xfc, 0xfa),
            list_name_fg:                   rgb(0x78, 0xdc, 0xe8),
            list_hash_fg:                   rgb(0xff, 0xd8, 0x66),
            list_date_fg:                   rgb(0xab, 0x9d, 0xf2),
            list_match_fg:                  rgb(0x2d, 0x2a, 0x2e),
            list_match_bg:                  rgb(0xff, 0xd8, 0x66),
            detail_label_fg:                rgb(0x72, 0x70, 0x72),
            detail_name_fg:                 rgb(0x78, 0xdc, 0xe8),
            detail_date_fg:                 rgb(0xab, 0x9d, 0xf2),
            detail_email_fg:                rgb(0x78, 0xdc, 0xe8),
            detail_hash_fg:                 rgb(0xff, 0xd8, 0x66),
            detail_ref_branch_fg:           rgb(0xa9, 0xdc, 0x76),
            detail_ref_remote_branch_fg:    rgb(0xff, 0x61, 0x88),
            detail_ref_tag_fg:              rgb(0xff, 0xd8, 0x66),
            detail_file_change_add_fg:      rgb(0xa9, 0xdc, 0x76),
            detail_file_change_modify_fg:   rgb(0xfc, 0x98, 0x67),
            detail_file_change_delete_fg:   rgb(0xff, 0x61, 0x88),
            detail_file_change_move_fg:     rgb(0x78, 0xdc, 0xe8),
            ref_selected_fg:                rgb(0xfc, 0xfc, 0xfa),
            ref_selected_bg:                rgb(0x40, 0x3e, 0x41),
            help_block_title_fg:            rgb(0xa9, 0xdc, 0x76),
            help_key_fg:                    rgb(0xff, 0xd8, 0x66),
            virtual_cursor_fg:              Color::Reset,
            status_input_fg:                Color::Reset,
            status_input_transient_fg:      rgb(0x72, 0x70, 0x72),
            status_info_fg:                 rgb(0x78, 0xdc, 0xe8),
            status_success_fg:              rgb(0xa9, 0xdc, 0x76),
            status_warn_fg:                 rgb(0xff, 0xd8, 0x66),
            status_error_fg:                rgb(0xff, 0x61, 0x88),
            divider_fg:                     rgb(0x40, 0x3e, 0x41),
        },
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn all_themes_are_listed() {
        assert_eq!(list_themes().len(), 10);
    }

    #[test]
    fn get_theme_returns_some_for_every_listed_name() {
        for name in list_themes() {
            assert!(get_theme(name).is_some(), "missing theme: {name}");
        }
    }

    #[test]
    fn get_theme_returns_none_for_unknown() {
        assert!(get_theme("not-a-theme").is_none());
    }
}
